class Hashable: pass
class Iterable: pass
class Iterator: pass
class Sized: pass
class Container: pass
class Collection: pass
class Mapping: pass
class MutableMapping: pass
class Sequence: pass
class MutableSequence: pass
class Set: pass
class MutableSet: pass
class Callable: pass
class Awaitable: pass
class Coroutine: pass
class AsyncIterable: pass
class AsyncIterator: pass
class AsyncGenerator: pass
class Generator: pass
