// Generated by protopyc from test_parse.py
#include <thread>
#include <protoCore.h>
#include <protoPython/PythonEnvironment.h>
#include <protoPython/Tokenizer.h>
#include <algorithm>


const proto::ProtoObject* py_func__f_1(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    try {
#line 2 "source.py"
/* pass */;
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}
extern "C" void* proto_module_init() {
    auto* ctx = protoPython::PythonEnvironment::getCurrentContext();
    auto* env = protoPython::PythonEnvironment::get(ctx);
    if (std::getenv("PROTO_ENV_DIAG")) {
        fprintf(stderr, "[mod] proto_module_init ctx=%p\n", (void*)ctx);
        const proto::ProtoObject* p = env->lookupName("print");
        fprintf(stderr, "[mod] lookupName('print')=%p\n", (void*)p);
        fflush(stderr);
    }

#line 1 "test_parse.py"
    const proto::ProtoObject* func__f = ctx->fromMethod(nullptr, py_func__f_1);
    env->storeName("_f", func__f);
#line 2 "test_parse.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("X")});
#line 3 "test_parse.py"
env->callObject(env->lookupName("print"), {env->callObject(env->lookupName("type"), {env->getAttr(env->lookupName("_f"), "__code__")})});
#line 4 "test_parse.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("Y")});
    return nullptr;
}
