// Generated by protopyc from test_lambda.py
#include <protoCore.h>
#include <protoPython/PythonEnvironment.h>
#include <protoPython/Tokenizer.h>

extern "C" void* proto_module_init() {
    auto* ctx = protoPython::PythonEnvironment::getCurrentContext();
    auto* env = protoPython::PythonEnvironment::get(ctx);

#line 1 "test_lambda.py"
env->storeName("f", ctx->fromMethod(nullptr, [](proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) -> const proto::ProtoObject* {
        auto* env = protoPython::PythonEnvironment::get(ctx);
        // Bind parameters
        if (args->getSize(ctx) > 0) env->storeName("x", args->getAt(ctx, 0));
        if (args->getSize(ctx) > 1) env->storeName("y", args->getAt(ctx, 1));
        return env->binaryOp(env->lookupName("x"), protoPython::TokenType::Plus, env->lookupName("y"));
    }));
#line 2 "test_lambda.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("1 + 2 ="), env->callObject(env->lookupName("f"), {ctx->fromInteger(1), ctx->fromInteger(2)})});
#line 4 "test_lambda.py"
env->storeName("g", ctx->fromMethod(nullptr, [](proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) -> const proto::ProtoObject* {
        auto* env = protoPython::PythonEnvironment::get(ctx);
        // Bind parameters
        return ctx->fromInteger(42);
    }));
#line 5 "test_lambda.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("g() ="), env->callObject(env->lookupName("g"), {})});
#line 7 "test_lambda.py"
env->storeName("h", ctx->fromMethod(nullptr, [](proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) -> const proto::ProtoObject* {
        auto* env = protoPython::PythonEnvironment::get(ctx);
        // Bind parameters
        if (args->getSize(ctx) > 0) env->storeName("x", args->getAt(ctx, 0));
        return ctx->fromMethod(nullptr, [](proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) -> const proto::ProtoObject* {
        auto* env = protoPython::PythonEnvironment::get(ctx);
        // Bind parameters
        if (args->getSize(ctx) > 0) env->storeName("y", args->getAt(ctx, 0));
        return env->binaryOp(env->lookupName("x"), protoPython::TokenType::Star, env->lookupName("y"));
    });
    }));
#line 8 "test_lambda.py"
env->storeName("mul2", env->callObject(env->lookupName("h"), {ctx->fromInteger(2)}));
#line 9 "test_lambda.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("2 * 3 ="), env->callObject(env->lookupName("mul2"), {ctx->fromInteger(3)})});
#line 12 "test_lambda.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("Sum [1,2,3]:"), env->callObject(ctx->fromMethod(nullptr, [](proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) -> const proto::ProtoObject* {
        auto* env = protoPython::PythonEnvironment::get(ctx);
        // Bind parameters
        if (args->getSize(ctx) > 0) env->storeName("l", args->getAt(ctx, 0));
        return env->binaryOp(env->binaryOp(env->getItem(env->lookupName("l"), ctx->fromInteger(0)), protoPython::TokenType::Plus, env->getItem(env->lookupName("l"), ctx->fromInteger(1))), protoPython::TokenType::Plus, env->getItem(env->lookupName("l"), ctx->fromInteger(2)));
    }), {([&]() {
        auto* listObj = static_cast<const proto::ProtoObject*>(ctx->newObject(true));
        auto* lst = ctx->newList();
        lst = lst->appendLast(ctx, ctx->fromInteger(1));
        lst = lst->appendLast(ctx, ctx->fromInteger(2));
        lst = lst->appendLast(ctx, ctx->fromInteger(3));
        listObj->setAttribute(ctx, env->getDataString(), (const proto::ProtoObject*)lst);
        if (env->getListPrototype()) listObj->addParent(ctx, env->getListPrototype());
        return (const proto::ProtoObject*)listObj;
    })()})});
    return nullptr;
}
