t = (1,)
print("isinstance(t, tuple) =", isinstance(t, tuple))
print("type(t) =", type(t))
print("tuple class =", tuple)
print("type(tuple) =", type(tuple))
print("t.__class__ =", getattr(t, '__class__', None))
