// Generated by protopyc from test_fstring.py
#include <protoCore.h>
#include <protoPython/PythonEnvironment.h>
#include <protoPython/Tokenizer.h>

extern "C" void* proto_module_init() {
    auto* ctx = protoPython::PythonEnvironment::getCurrentContext();
    auto* env = protoPython::PythonEnvironment::get(ctx);

#line 1 "test_fstring.py"
env->storeName("name", ctx->fromUTF8String("World"));
#line 2 "test_fstring.py"
env->storeName("x", ctx->fromInteger(10));
#line 3 "test_fstring.py"
env->storeName("y", ctx->fromInteger(20));
#line 4 "test_fstring.py"
env->storeName("s", env->buildString({ctx->fromUTF8String("Hello, "), env->lookupName("name"), ctx->fromUTF8String("! x + y = "), env->binaryOp(env->lookupName("x"), protoPython::TokenType::Plus, env->lookupName("y"))}));
#line 5 "test_fstring.py"
env->callObject(env->lookupName("print"), {env->lookupName("s")});
#line 7 "test_fstring.py"
/* Unsupported node: N11protoPython10AssertNodeE */;
#line 10 "test_fstring.py"
env->storeName("s2", env->buildString({ctx->fromUTF8String("{"), ctx->fromUTF8String("brace"), ctx->fromUTF8String("}"), ctx->fromUTF8String(" "), env->lookupName("x")}));
#line 11 "test_fstring.py"
env->callObject(env->lookupName("print"), {env->lookupName("s2")});
#line 12 "test_fstring.py"
/* Unsupported node: N11protoPython10AssertNodeE */;
#line 15 "test_fstring.py"
env->storeName("s3", env->buildString({env->getItem(([&]() {
        auto* listObj = static_cast<const proto::ProtoObject*>(ctx->newObject(true));
        auto* lst = ctx->newList();
        lst = lst->appendLast(ctx, ctx->fromInteger(1));
        lst = lst->appendLast(ctx, ctx->fromInteger(2));
        lst = lst->appendLast(ctx, ctx->fromInteger(3));
        listObj->setAttribute(ctx, env->getDataString(), (const proto::ProtoObject*)lst);
        if (env->getListPrototype()) listObj->addParent(ctx, env->getListPrototype());
        return (const proto::ProtoObject*)listObj;
    })(), ctx->fromInteger(1))}));
#line 16 "test_fstring.py"
env->callObject(env->lookupName("print"), {env->lookupName("s3")});
#line 17 "test_fstring.py"
/* Unsupported node: N11protoPython10AssertNodeE */;
#line 19 "test_fstring.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("F-String tests passed!")});
    return nullptr;
}
