// Generated by protopyc from test_dump.py
#include <thread>
#include <protoCore.h>
#include <protoPython/PythonEnvironment.h>
#include <protoPython/Tokenizer.h>
#include <algorithm>


const proto::ProtoObject* py_func_f_1(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_d = PROTO_NONE;
    try {
#line 2 "source.py"
env->storeName("d", ([&]() {
        auto* mapObj = static_cast<const proto::ProtoObject*>(ctx->newObject(true));
        auto* data = ctx->newSparseList();
        auto* keys = ctx->newList();
        {
            auto* k = ctx->fromUTF8String("a");
            auto* v = ctx->fromInteger(1);
            data = data->setAt(ctx, k->getHash(ctx), v);
            keys = keys->appendLast(ctx, k);
        }
        {
            auto* k = ctx->fromUTF8String("b");
            auto* v = ctx->fromInteger(2);
            data = data->setAt(ctx, k->getHash(ctx), v);
            keys = keys->appendLast(ctx, k);
        }
        mapObj->setAttribute(ctx, env->getDataString(), (const proto::ProtoObject*)data);
        mapObj->setAttribute(ctx, env->getKeysString(), (const proto::ProtoObject*)keys);
        if (env->getDictPrototype()) mapObj->addParent(ctx, env->getDictPrototype());
        return (const proto::ProtoObject*)mapObj;
    })());
#line 3 "source.py"
throw /* Unsupported node: N11protoPython16GeneratorExpNodeE */;
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}
extern "C" void* proto_module_init() {
    auto* ctx = protoPython::PythonEnvironment::getCurrentContext();
    auto* env = protoPython::PythonEnvironment::get(ctx);
    if (std::getenv("PROTO_ENV_DIAG")) {
        fprintf(stderr, "[mod] proto_module_init ctx=%p\n", (void*)ctx);
        const proto::ProtoObject* p = env->lookupName("print");
        fprintf(stderr, "[mod] lookupName('print')=%p\n", (void*)p);
        fflush(stderr);
    }

#line 1 "test_dump.py"
    const proto::ProtoObject* func_f = ctx->fromMethod(nullptr, py_func_f_1);
    env->storeName("f", func_f);
    return nullptr;
}
