print("bytes_iterator:", type(iter(b'')))
print("bytearray_iterator:", type(iter(bytearray())))
print("dict_keyiterator:", type(iter({}.keys())))
print("dict_valueiterator:", type(iter({}.values())))
print("dict_itemiterator:", type(iter({}.items())))
print("list_iterator:", type(iter([])))
print("list_reverseiterator:", type(reversed([])))
print("range_iterator:", type(iter(range(0))))
print("longrange_iterator:", type(iter(range(1 << 1000))))
print("set_iterator:", type(iter(set())))
print("str_iterator:", type(iter("")))
print("tuple_iterator:", type(iter(())))
print("zip_iterator:", type(iter(zip())))
