// Generated by protopyc from lib/python3.14/types.py
#include <thread>
#include <protoCore.h>
#include <protoPython/PythonEnvironment.h>
#include <protoPython/Tokenizer.h>
#include <algorithm>


const proto::ProtoObject* py_func__f_1(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    try {
#line 16 "source.py"
/* pass */;
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_f_3(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    try {
#line 25 "source.py"
/* Unsupported node: N11protoPython12NonlocalNodeE */;
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func__cell_factory_2(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_a = PROTO_NONE;
    try {
#line 23 "source.py"
env->storeName("a", ctx->fromInteger(1));
#line 24 "source.py"
    const proto::ProtoObject* func_f = ctx->fromMethod(nullptr, py_func_f_3);
    env->storeName("f", func_f);
#line 26 "source.py"
throw env->getItem(env->getAttr(env->lookupName("f"), "__closure__"), ctx->fromInteger(0));
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_cont__g_4(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    auto* gen = const_cast<proto::ProtoObject*>(self);
    const proto::ProtoSparseList* gi_locals = env->getAttribute(ctx, gen, env->getGiLocalsString())->asSparseList(ctx);
    int pc = env->getAttribute(ctx, gen, env->getGiPCString())->asLong(ctx);
    if (std::getenv("PROTO_ENV_DIAG")) { fprintf(stderr, "[cont] gen=%p pc=%d\n", (void*)gen, pc); fflush(stderr); }
    try {
        switch (pc) {
            case 0: 
#line 30 "source.py"
            {
                const proto::ProtoSparseList* locals = ctx->newSparseList();
                gen->setAttribute(ctx, env->getGiLocalsString(), locals->asObject(ctx));
            }
            gen->setAttribute(ctx, env->getGiPCString(), ctx->fromInteger(1));
            throw ctx->fromInteger(1);
        case 1:
            /* resumed from yield */
            if (std::getenv("PROTO_ENV_DIAG")) { fprintf(stderr, "[cont] resumed yield pc=1\n"); fflush(stderr); }
            ([&]() -> const proto::ProtoObject* {
                return (args && args->getSize(ctx) > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
            })();
                break;
        }
    } catch (const proto::ProtoObject* val) {
        if (env->isStopIteration(val)) throw val;
        return val;
    }
    gen->setAttribute(ctx, env->getGiPCString(), ctx->fromInteger(-1));
    env->raiseStopIteration(ctx, PROTO_NONE);
    return PROTO_NONE;
}

const proto::ProtoObject* py_func__g_4(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    auto* gen = const_cast<proto::ProtoObject*>(ctx->newObject(true));
    if (env->getGeneratorPrototype()) gen->addParent(ctx, env->getGeneratorPrototype());
    gen = const_cast<proto::ProtoObject*>(gen->setAttribute(ctx, env->getGiNativeCallbackString(), ctx->fromMethod(nullptr, py_cont__g_4)));
    gen = const_cast<proto::ProtoObject*>(gen->setAttribute(ctx, env->getGiPCString(), ctx->fromInteger(0)));
    gen = const_cast<proto::ProtoObject*>(gen->setAttribute(ctx, env->getGiRunningString(), PROTO_FALSE));
    const proto::ProtoSparseList* initialLocals = ctx->newSparseList();
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    gen = const_cast<proto::ProtoObject*>(gen->setAttribute(ctx, env->getGiLocalsString(), initialLocals->asObject(ctx)));
    return gen;
}

const proto::ProtoObject* py_func__c_5(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    try {
#line 34 "source.py"
/* pass */;
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_cont__ag_6(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    auto* gen = const_cast<proto::ProtoObject*>(self);
    const proto::ProtoSparseList* gi_locals = env->getAttribute(ctx, gen, env->getGiLocalsString())->asSparseList(ctx);
    int pc = env->getAttribute(ctx, gen, env->getGiPCString())->asLong(ctx);
    if (std::getenv("PROTO_ENV_DIAG")) { fprintf(stderr, "[cont] gen=%p pc=%d\n", (void*)gen, pc); fflush(stderr); }
    try {
        switch (pc) {
            case 0: 
#line 40 "source.py"
            {
                const proto::ProtoSparseList* locals = ctx->newSparseList();
                gen->setAttribute(ctx, env->getGiLocalsString(), locals->asObject(ctx));
            }
            gen->setAttribute(ctx, env->getGiPCString(), ctx->fromInteger(1));
            throw PROTO_NONE;
        case 1:
            /* resumed from yield */
            if (std::getenv("PROTO_ENV_DIAG")) { fprintf(stderr, "[cont] resumed yield pc=1\n"); fflush(stderr); }
            ([&]() -> const proto::ProtoObject* {
                return (args && args->getSize(ctx) > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
            })();
                break;
        }
    } catch (const proto::ProtoObject* val) {
        if (env->isStopIteration(val)) throw val;
        return val;
    }
    gen->setAttribute(ctx, env->getGiPCString(), ctx->fromInteger(-1));
    env->raiseStopIteration(ctx, PROTO_NONE);
    return PROTO_NONE;
}

const proto::ProtoObject* py_func__ag_6(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    auto* gen = const_cast<proto::ProtoObject*>(ctx->newObject(true));
    if (env->getGeneratorPrototype()) gen->addParent(ctx, env->getGeneratorPrototype());
    gen = const_cast<proto::ProtoObject*>(gen->setAttribute(ctx, env->getGiNativeCallbackString(), ctx->fromMethod(nullptr, py_cont__ag_6)));
    gen = const_cast<proto::ProtoObject*>(gen->setAttribute(ctx, env->getGiPCString(), ctx->fromInteger(0)));
    gen = const_cast<proto::ProtoObject*>(gen->setAttribute(ctx, env->getGiRunningString(), PROTO_FALSE));
    const proto::ProtoSparseList* initialLocals = ctx->newSparseList();
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    gen = const_cast<proto::ProtoObject*>(gen->setAttribute(ctx, env->getGiLocalsString(), initialLocals->asObject(ctx)));
    return gen;
}

const proto::ProtoObject* py_func__m_7(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    try {
#line 45 "source.py"
/* pass */;
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_new_class_8(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_name = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_bases = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    const proto::ProtoObject* local_kwds = (nPos > 2) ? args->getAt(ctx, 2) : PROTO_NONE;
    const proto::ProtoObject* local_exec_body = (nPos > 3) ? args->getAt(ctx, 3) : PROTO_NONE;
    const proto::ProtoObject* local_resolved_bases = PROTO_NONE;
    try {
#line 82 "source.py"
ctx->fromUTF8String("Create a class object dynamically using the appropriate metaclass.");
#line 82 "source.py"
env->storeName("resolved_bases", env->callObject(env->lookupName("resolve_bases"), {env->lookupName("bases")}));
#line 83 "source.py"
/* Unsupported assignment target */;
#line 86 "source.py"
if (env->isTrue(env->binaryOp(env->lookupName("exec_body"), protoPython::TokenType::Plus /* Unsupported op */, PROTO_NONE))) {
#line 85 "source.py"
env->callObject(env->lookupName("exec_body"), {env->lookupName("ns")});
;
};
#line 88 "source.py"
if (env->isTrue(env->binaryOp(env->lookupName("resolved_bases"), protoPython::TokenType::Plus /* Unsupported op */, env->lookupName("bases")))) {
#line 87 "source.py"
env->setItem(env->lookupName("ns"), ctx->fromUTF8String("__orig_bases__"), env->lookupName("bases"));
;
};
#line 88 "source.py"
throw ([&]() {
        auto* __f = env->lookupName("meta");
        auto* __alst = ctx->newList();
        __alst = __alst->appendLast(ctx, env->lookupName("name"));
        __alst = __alst->appendLast(ctx, env->lookupName("resolved_bases"));
        __alst = __alst->appendLast(ctx, env->lookupName("ns"));
        bool __hasKw = false;
        auto* __kmap = ctx->newSparseList();
        __hasKw = true;
        __kmap = ctx->dictUpdate(ctx, __kmap, (const proto::ProtoSparseList*)env->getAttr(env->lookupName("kwds"), env->getDataString()));
        return env->callObjectEx(__f, {}, {}, ctx->newTupleFromList(__alst)->asObject(ctx), __hasKw ? __kmap->asObject(ctx) : nullptr);
    })();
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_resolve_bases_9(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_bases = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_new_base = PROTO_NONE;
    const proto::ProtoObject* local_new_bases = PROTO_NONE;
    const proto::ProtoObject* local_shift = PROTO_NONE;
    const proto::ProtoObject* local_updated = PROTO_NONE;
    try {
#line 92 "source.py"
ctx->fromUTF8String("Resolve MRO entries dynamically as specified by PEP 560.");
#line 92 "source.py"
env->storeName("new_bases", env->callObject(env->lookupName("list"), {env->lookupName("bases")}));
#line 93 "source.py"
env->storeName("updated", PROTO_FALSE);
#line 94 "source.py"
env->storeName("shift", ctx->fromInteger(0));
#line 107 "source.py"
{
        auto* __iter_0 = env->iter(env->callObject(env->lookupName("enumerate"), {env->lookupName("bases")}));
        while (true) {
            auto* __val_0 = env->next(__iter_0);
            if (env->hasPendingException()) {
                (void)env->takePendingException();
                break;
            }
            if (!__val_0 || __val_0 == PROTO_NONE) {
                break;
            }
/* Unsupported assignment target */;
#line 98 "source.py"
if (env->isTrue(env->callObject(env->lookupName("isinstance"), {env->lookupName("base"), env->lookupName("type")}))) {
#line 98 "source.py"
continue;
;
};
#line 100 "source.py"
if (env->isTrue(env->unaryOp(protoPython::TokenType::Not, env->callObject(env->lookupName("hasattr"), {env->lookupName("base"), ctx->fromUTF8String("__mro_entries__")})))) {
#line 100 "source.py"
continue;
;
};
#line 100 "source.py"
env->storeName("new_base", env->callObject(env->getAttr(env->lookupName("base"), "__mro_entries__"), {env->lookupName("bases")}));
#line 101 "source.py"
env->storeName("updated", PROTO_TRUE);
#line 104 "source.py"
if (env->isTrue(env->unaryOp(protoPython::TokenType::Not, env->callObject(env->lookupName("isinstance"), {env->lookupName("new_base"), env->lookupName("tuple")})))) {
#line 103 "source.py"
env->raiseException(env->callObject(env->lookupName("TypeError"), {ctx->fromUTF8String("__mro_entries__ must return a tuple")}));
;
} else {
#line 105 "source.py"
env->setItem(env->lookupName("new_bases"), env->buildSlice(env->binaryOp(env->lookupName("i"), protoPython::TokenType::Plus, env->lookupName("shift")), env->binaryOp(env->binaryOp(env->lookupName("i"), protoPython::TokenType::Plus, env->lookupName("shift")), protoPython::TokenType::Plus, ctx->fromInteger(1)), PROTO_NONE), env->lookupName("new_base"));
#line 107 "source.py"
env->augAssignName("shift", protoPython::TokenType::PlusAssign, env->binaryOp(env->callObject(env->lookupName("len"), {env->lookupName("new_base")}), protoPython::TokenType::Minus, ctx->fromInteger(1)));
;
};
        }
    };
#line 109 "source.py"
if (env->isTrue(env->unaryOp(protoPython::TokenType::Not, env->lookupName("updated")))) {
#line 108 "source.py"
throw env->lookupName("bases");
;
};
#line 109 "source.py"
throw env->callObject(env->lookupName("tuple"), {env->lookupName("new_bases")});
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_prepare_class_10(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_name = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_bases = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    const proto::ProtoObject* local_kwds = (nPos > 2) ? args->getAt(ctx, 2) : PROTO_NONE;
    const proto::ProtoObject* local_meta = PROTO_NONE;
    const proto::ProtoObject* local_ns = PROTO_NONE;
    try {
#line 122 "source.py"
ctx->fromUTF8String("Call the __prepare__ method of the appropriate metaclass.

    Returns (metaclass, namespace, kwds) as a 3-tuple

    *metaclass* is the appropriate metaclass
    *namespace* is the prepared class namespace
    *kwds* is an updated copy of the passed in kwds argument with any
    'metaclass' entry removed. If no kwds argument is passed in, this will
    be an empty dict.
    ");
#line 124 "source.py"
if (env->isTrue(env->binaryOp(env->lookupName("kwds"), protoPython::TokenType::Plus /* Unsupported op */, PROTO_NONE))) {
#line 123 "source.py"
env->storeName("kwds", ([&]() {
        auto* mapObj = static_cast<const proto::ProtoObject*>(ctx->newObject(true));
        auto* data = ctx->newSparseList();
        auto* keys = ctx->newList();
        mapObj->setAttribute(ctx, env->getDataString(), (const proto::ProtoObject*)data);
        mapObj->setAttribute(ctx, env->getKeysString(), (const proto::ProtoObject*)keys);
        if (env->getDictPrototype()) mapObj->addParent(ctx, env->getDictPrototype());
        return (const proto::ProtoObject*)mapObj;
    })());
;
} else {
#line 125 "source.py"
env->storeName("kwds", env->callObject(env->lookupName("dict"), {env->lookupName("kwds")}));
;
};
#line 128 "source.py"
if (env->isTrue(env->binaryOp(ctx->fromUTF8String("metaclass"), protoPython::TokenType::Plus /* Unsupported op */, env->lookupName("kwds")))) {
#line 127 "source.py"
env->storeName("meta", env->callObject(env->getAttr(env->lookupName("kwds"), "pop"), {ctx->fromUTF8String("metaclass")}));
;
} else {
#line 131 "source.py"
if (env->isTrue(env->lookupName("bases"))) {
#line 130 "source.py"
env->storeName("meta", env->callObject(env->lookupName("type"), {env->getItem(env->lookupName("bases"), ctx->fromInteger(0))}));
;
} else {
#line 132 "source.py"
env->storeName("meta", env->lookupName("type"));
;
};
;
};
#line 137 "source.py"
if (env->isTrue(env->callObject(env->lookupName("isinstance"), {env->lookupName("meta"), env->lookupName("type")}))) {
#line 136 "source.py"
env->storeName("meta", env->callObject(env->lookupName("_calculate_meta"), {env->lookupName("meta"), env->lookupName("bases")}));
;
};
#line 139 "source.py"
if (env->isTrue(env->callObject(env->lookupName("hasattr"), {env->lookupName("meta"), ctx->fromUTF8String("__prepare__")}))) {
#line 138 "source.py"
env->storeName("ns", ([&]() {
        auto* __f = env->getAttr(env->lookupName("meta"), "__prepare__");
        auto* __alst = ctx->newList();
        __alst = __alst->appendLast(ctx, env->lookupName("name"));
        __alst = __alst->appendLast(ctx, env->lookupName("bases"));
        bool __hasKw = false;
        auto* __kmap = ctx->newSparseList();
        __hasKw = true;
        __kmap = ctx->dictUpdate(ctx, __kmap, (const proto::ProtoSparseList*)env->getAttr(env->lookupName("kwds"), env->getDataString()));
        return env->callObjectEx(__f, {}, {}, ctx->newTupleFromList(__alst)->asObject(ctx), __hasKw ? __kmap->asObject(ctx) : nullptr);
    })());
;
} else {
#line 140 "source.py"
env->storeName("ns", ([&]() {
        auto* mapObj = static_cast<const proto::ProtoObject*>(ctx->newObject(true));
        auto* data = ctx->newSparseList();
        auto* keys = ctx->newList();
        mapObj->setAttribute(ctx, env->getDataString(), (const proto::ProtoObject*)data);
        mapObj->setAttribute(ctx, env->getKeysString(), (const proto::ProtoObject*)keys);
        if (env->getDictPrototype()) mapObj->addParent(ctx, env->getDictPrototype());
        return (const proto::ProtoObject*)mapObj;
    })());
;
};
#line 141 "source.py"
throw ([&]() {
        auto* tupObj = static_cast<const proto::ProtoObject*>(ctx->newObject(true));
        auto* lst = ctx->newList();
        lst = lst->appendLast(ctx, env->lookupName("meta"));
        lst = lst->appendLast(ctx, env->lookupName("ns"));
        lst = lst->appendLast(ctx, env->lookupName("kwds"));
        auto* tup = ctx->newTupleFromList(lst);
        tupObj->setAttribute(ctx, env->getDataString(), (const proto::ProtoObject*)tup);
        if (env->getTuplePrototype()) tupObj->addParent(ctx, env->getTuplePrototype());
        return (const proto::ProtoObject*)tupObj;
    })();
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func__calculate_meta_11(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_meta = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_bases = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    const proto::ProtoObject* local_base = PROTO_NONE;
    const proto::ProtoObject* local_base_meta = PROTO_NONE;
    const proto::ProtoObject* local_winner = PROTO_NONE;
    try {
#line 145 "source.py"
ctx->fromUTF8String("Calculate the most derived metaclass.");
#line 145 "source.py"
env->storeName("winner", env->lookupName("meta"));
#line 158 "source.py"
{
        auto* __iter_1 = env->iter(env->lookupName("bases"));
        while (true) {
            auto* __val_1 = env->next(__iter_1);
            if (env->hasPendingException()) {
                (void)env->takePendingException();
                break;
            }
            if (!__val_1 || __val_1 == PROTO_NONE) {
                break;
            }
            env->storeName("base", __val_1);
#line 147 "source.py"
env->storeName("base_meta", env->callObject(env->lookupName("type"), {env->lookupName("base")}));
#line 150 "source.py"
if (env->isTrue(env->callObject(env->lookupName("issubclass"), {env->lookupName("winner"), env->lookupName("base_meta")}))) {
#line 150 "source.py"
continue;
;
};
#line 154 "source.py"
if (env->isTrue(env->callObject(env->lookupName("issubclass"), {env->lookupName("base_meta"), env->lookupName("winner")}))) {
#line 151 "source.py"
env->storeName("winner", env->lookupName("base_meta"));
#line 153 "source.py"
continue;
;
};
#line 154 "source.py"
env->raiseException(env->callObject(env->lookupName("TypeError"), {ctx->fromUTF8String("metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases")}));
        }
    };
#line 158 "source.py"
throw env->lookupName("winner");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_get_original_bases_12(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_cls = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    try {
#line 181 "source.py"
ctx->fromUTF8String("Return the class's "original" bases prior to modification by `__mro_entries__`.

    Examples::

        from typing import TypeVar, Generic, NamedTuple, TypedDict

        T = TypeVar("T")
        class Foo(Generic[T]): ...
        class Bar(Foo[int], float): ...
        class Baz(list[str]): ...
        Eggs = NamedTuple("Eggs", [("a", int), ("b", str)])
        Spam = TypedDict("Spam", {"a": int, "b": str})

        assert get_original_bases(Bar) == (Foo[int], float)
        assert get_original_bases(Baz) == (list[str],)
        assert get_original_bases(Eggs) == (NamedTuple,)
        assert get_original_bases(Spam) == (TypedDict,)
        assert get_original_bases(int) == (object,)
    ");
#line 182 "source.py"
{
#line 182 "source.py"
throw env->callObject(env->getAttr(env->getAttr(env->lookupName("cls"), "__dict__"), "get"), {ctx->fromUTF8String("__orig_bases__"), env->getAttr(env->lookupName("cls"), "__bases__")});
        if (env->hasPendingException()) {
            auto* __exc = env->takePendingException();
            bool __handled = false;
            if (!__handled && env->isException(__exc, env->lookupName("AttributeError"))) {
                __handled = true;
#line 184 "source.py"
env->raiseException(env->callObject(env->lookupName("TypeError"), {env->buildString({ctx->fromUTF8String("Expected an instance of type, not "), env->getAttr(env->callObject(env->lookupName("type"), {env->lookupName("cls")}), "__name__")})}));
            }
            if (!__handled) env->raiseException(__exc);
        }
    };
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func___init___13(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_fget = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    const proto::ProtoObject* local_fset = (nPos > 2) ? args->getAt(ctx, 2) : PROTO_NONE;
    const proto::ProtoObject* local_fdel = (nPos > 3) ? args->getAt(ctx, 3) : PROTO_NONE;
    const proto::ProtoObject* local_doc = (nPos > 4) ? args->getAt(ctx, 4) : PROTO_NONE;
    try {
#line 207 "source.py"
env->setAttr(env->lookupName("self"), "fget", env->lookupName("fget"));
#line 208 "source.py"
env->setAttr(env->lookupName("self"), "fset", env->lookupName("fset"));
#line 209 "source.py"
env->setAttr(env->lookupName("self"), "fdel", env->lookupName("fdel"));
#line 211 "source.py"
env->setAttr(env->lookupName("self"), "__doc__", env->binaryOp(env->lookupName("doc"), protoPython::TokenType::Plus /* Unsupported op */, env->getAttr(env->lookupName("fget"), "__doc__")));
#line 212 "source.py"
env->setAttr(env->lookupName("self"), "overwrite_doc", env->binaryOp(env->lookupName("doc"), protoPython::TokenType::Plus /* Unsupported op */, PROTO_NONE));
#line 214 "source.py"
env->setAttr(env->lookupName("self"), "__isabstractmethod__", env->callObject(env->lookupName("bool"), {env->callObject(env->lookupName("getattr"), {env->lookupName("fget"), ctx->fromUTF8String("__isabstractmethod__"), PROTO_FALSE})}));
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func___get___14(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_instance = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    const proto::ProtoObject* local_ownerclass = (nPos > 2) ? args->getAt(ctx, 2) : PROTO_NONE;
    try {
#line 221 "source.py"
if (env->isTrue(env->binaryOp(env->lookupName("instance"), protoPython::TokenType::Plus /* Unsupported op */, PROTO_NONE))) {
#line 220 "source.py"
if (env->isTrue(env->getAttr(env->lookupName("self"), "__isabstractmethod__"))) {
#line 219 "source.py"
throw env->lookupName("self");
;
};
#line 220 "source.py"
env->raiseException(env->callObject(env->lookupName("AttributeError"), {}));
;
} else {
if (env->isTrue(env->binaryOp(env->getAttr(env->lookupName("self"), "fget"), protoPython::TokenType::Plus /* Unsupported op */, PROTO_NONE))) {
#line 222 "source.py"
env->raiseException(env->callObject(env->lookupName("AttributeError"), {ctx->fromUTF8String("unreadable attribute")}));
;
};
};
#line 223 "source.py"
throw env->callObject(env->getAttr(env->lookupName("self"), "fget"), {env->lookupName("instance")});
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func___set___15(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_instance = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    const proto::ProtoObject* local_value = (nPos > 2) ? args->getAt(ctx, 2) : PROTO_NONE;
    try {
#line 228 "source.py"
if (env->isTrue(env->binaryOp(env->getAttr(env->lookupName("self"), "fset"), protoPython::TokenType::Plus /* Unsupported op */, PROTO_NONE))) {
#line 227 "source.py"
env->raiseException(env->callObject(env->lookupName("AttributeError"), {ctx->fromUTF8String("can't set attribute")}));
;
};
#line 228 "source.py"
env->callObject(env->getAttr(env->lookupName("self"), "fset"), {env->lookupName("instance"), env->lookupName("value")});
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func___delete___16(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_instance = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    try {
#line 233 "source.py"
if (env->isTrue(env->binaryOp(env->getAttr(env->lookupName("self"), "fdel"), protoPython::TokenType::Plus /* Unsupported op */, PROTO_NONE))) {
#line 232 "source.py"
env->raiseException(env->callObject(env->lookupName("AttributeError"), {ctx->fromUTF8String("can't delete attribute")}));
;
};
#line 233 "source.py"
env->callObject(env->getAttr(env->lookupName("self"), "fdel"), {env->lookupName("instance")});
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_getter_17(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_fget = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    const proto::ProtoObject* local_fdoc = PROTO_NONE;
    const proto::ProtoObject* local_result = PROTO_NONE;
    try {
#line 236 "source.py"
env->storeName("fdoc", /* Unsupported node: N11protoPython19ConditionalExprNodeE */);
#line 237 "source.py"
env->storeName("result", env->callObject(env->callObject(env->lookupName("type"), {env->lookupName("self")}), {env->lookupName("fget"), env->getAttr(env->lookupName("self"), "fset"), env->getAttr(env->lookupName("self"), "fdel"), env->binaryOp(env->lookupName("fdoc"), protoPython::TokenType::Plus /* Unsupported op */, env->getAttr(env->lookupName("self"), "__doc__"))}));
#line 238 "source.py"
env->setAttr(env->lookupName("result"), "overwrite_doc", env->getAttr(env->lookupName("self"), "overwrite_doc"));
#line 239 "source.py"
throw env->lookupName("result");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_setter_18(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_fset = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    const proto::ProtoObject* local_result = PROTO_NONE;
    try {
#line 242 "source.py"
env->storeName("result", env->callObject(env->callObject(env->lookupName("type"), {env->lookupName("self")}), {env->getAttr(env->lookupName("self"), "fget"), env->lookupName("fset"), env->getAttr(env->lookupName("self"), "fdel"), env->getAttr(env->lookupName("self"), "__doc__")}));
#line 243 "source.py"
env->setAttr(env->lookupName("result"), "overwrite_doc", env->getAttr(env->lookupName("self"), "overwrite_doc"));
#line 244 "source.py"
throw env->lookupName("result");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_deleter_19(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_fdel = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    const proto::ProtoObject* local_result = PROTO_NONE;
    try {
#line 247 "source.py"
env->storeName("result", env->callObject(env->callObject(env->lookupName("type"), {env->lookupName("self")}), {env->getAttr(env->lookupName("self"), "fget"), env->getAttr(env->lookupName("self"), "fset"), env->lookupName("fdel"), env->getAttr(env->lookupName("self"), "__doc__")}));
#line 248 "source.py"
env->setAttr(env->lookupName("result"), "overwrite_doc", env->getAttr(env->lookupName("self"), "overwrite_doc"));
#line 249 "source.py"
throw env->lookupName("result");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func___init___20(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_gen = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    try {
#line 255 "source.py"
env->setAttr(env->lookupName("self"), "__wrapped", env->lookupName("gen"));
#line 256 "source.py"
env->setAttr(env->lookupName("self"), "__isgen", env->binaryOp(env->getAttr(env->lookupName("gen"), "__class__"), protoPython::TokenType::Plus /* Unsupported op */, env->lookupName("GeneratorType")));
#line 257 "source.py"
env->setAttr(env->lookupName("self"), "__name__", env->callObject(env->lookupName("getattr"), {env->lookupName("gen"), ctx->fromUTF8String("__name__"), PROTO_NONE}));
#line 258 "source.py"
env->setAttr(env->lookupName("self"), "__qualname__", env->callObject(env->lookupName("getattr"), {env->lookupName("gen"), ctx->fromUTF8String("__qualname__"), PROTO_NONE}));
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_send_21(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_val = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    try {
#line 260 "source.py"
throw env->callObject(env->getAttr(env->getAttr(env->lookupName("self"), "__wrapped"), "send"), {env->lookupName("val")});
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_throw_22(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_tp = (nPos > 1) ? args->getAt(ctx, 1) : PROTO_NONE;
    try {
#line 262 "source.py"
throw ([&]() {
        auto* __f = env->getAttr(env->getAttr(env->lookupName("self"), "__wrapped"), "throw");
        auto* __alst = ctx->newList();
        __alst = __alst->appendLast(ctx, env->lookupName("tp"));
        __alst = ctx->listExtend(ctx, __alst, (const proto::ProtoList*)env->getAttr(env->lookupName("rest"), env->getDataString()));
        bool __hasKw = false;
        auto* __kmap = ctx->newSparseList();
        return env->callObjectEx(__f, {}, {}, ctx->newTupleFromList(__alst)->asObject(ctx), __hasKw ? __kmap->asObject(ctx) : nullptr);
    })();
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_close_23(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    try {
#line 264 "source.py"
throw env->callObject(env->getAttr(env->getAttr(env->lookupName("self"), "__wrapped"), "close"), {});
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_gi_code_24(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    try {
#line 267 "source.py"
throw env->getAttr(env->getAttr(env->lookupName("self"), "__wrapped"), "gi_code");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_gi_frame_25(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    try {
#line 270 "source.py"
throw env->getAttr(env->getAttr(env->lookupName("self"), "__wrapped"), "gi_frame");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_gi_running_26(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    try {
#line 273 "source.py"
throw env->getAttr(env->getAttr(env->lookupName("self"), "__wrapped"), "gi_running");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_gi_yieldfrom_27(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    try {
#line 276 "source.py"
throw env->getAttr(env->getAttr(env->lookupName("self"), "__wrapped"), "gi_yieldfrom");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func___next___28(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    try {
#line 282 "source.py"
throw env->callObject(env->lookupName("next"), {env->getAttr(env->lookupName("self"), "__wrapped")});
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func___iter___29(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_self = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    try {
#line 286 "source.py"
if (env->isTrue(env->getAttr(env->lookupName("self"), "__isgen"))) {
#line 285 "source.py"
throw env->getAttr(env->lookupName("self"), "__wrapped");
;
};
#line 286 "source.py"
throw env->lookupName("self");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_wrapped_31(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_coro = PROTO_NONE;
    try {
#line 323 "source.py"
env->storeName("coro", ([&]() {
        auto* __f = env->lookupName("func");
        auto* __alst = ctx->newList();
        __alst = ctx->listExtend(ctx, __alst, (const proto::ProtoList*)env->getAttr(env->lookupName("args"), env->getDataString()));
        bool __hasKw = false;
        auto* __kmap = ctx->newSparseList();
        __hasKw = true;
        __kmap = ctx->dictUpdate(ctx, __kmap, (const proto::ProtoSparseList*)env->getAttr(env->lookupName("kwargs"), env->getDataString()));
        return env->callObjectEx(__f, {}, {}, ctx->newTupleFromList(__alst)->asObject(ctx), __hasKw ? __kmap->asObject(ctx) : nullptr);
    })());
#line 328 "source.py"
if (env->isTrue(env->binaryOp(env->binaryOp(env->getAttr(env->lookupName("coro"), "__class__"), protoPython::TokenType::Plus /* Unsupported op */, env->lookupName("CoroutineType")), protoPython::TokenType::Plus /* Unsupported op */, env->binaryOp(env->binaryOp(env->getAttr(env->lookupName("coro"), "__class__"), protoPython::TokenType::Plus /* Unsupported op */, env->lookupName("GeneratorType")), protoPython::TokenType::Plus /* Unsupported op */, env->binaryOp(env->getAttr(env->getAttr(env->lookupName("coro"), "gi_code"), "co_flags"), protoPython::TokenType::BitAnd, ctx->fromInteger(256)))))) {
#line 327 "source.py"
throw env->lookupName("coro");
;
};
#line 336 "source.py"
if (env->isTrue(env->binaryOp(env->callObject(env->lookupName("isinstance"), {env->lookupName("coro"), env->getAttr(env->lookupName("_collections_abc"), "Generator")}), protoPython::TokenType::Plus /* Unsupported op */, env->unaryOp(protoPython::TokenType::Not, env->callObject(env->lookupName("isinstance"), {env->lookupName("coro"), env->getAttr(env->lookupName("_collections_abc"), "Coroutine")}))))) {
#line 333 "source.py"
throw env->callObject(env->lookupName("_GeneratorWrapper"), {env->lookupName("coro")});
;
};
#line 336 "source.py"
throw env->lookupName("coro");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}

const proto::ProtoObject* py_func_coroutine_30(proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) {
    auto* env = protoPython::PythonEnvironment::get(ctx);
    unsigned long nPos = args ? args->getSize(ctx) : 0;
    const proto::ProtoObject* local_func = (nPos > 0) ? args->getAt(ctx, 0) : PROTO_NONE;
    const proto::ProtoObject* local_co = PROTO_NONE;
    const proto::ProtoObject* local_co_flags = PROTO_NONE;
    try {
#line 291 "source.py"
ctx->fromUTF8String("Convert regular generator function to a coroutine.");
#line 295 "source.py"
if (env->isTrue(env->unaryOp(protoPython::TokenType::Not, env->callObject(env->lookupName("callable"), {env->lookupName("func")})))) {
#line 293 "source.py"
env->raiseException(env->callObject(env->lookupName("TypeError"), {ctx->fromUTF8String("types.coroutine() expects a callable")}));
;
};
#line 319 "source.py"
if (env->isTrue(env->binaryOp(env->binaryOp(env->getAttr(env->lookupName("func"), "__class__"), protoPython::TokenType::Plus /* Unsupported op */, env->lookupName("FunctionType")), protoPython::TokenType::Plus /* Unsupported op */, env->binaryOp(env->getAttr(env->callObject(env->lookupName("getattr"), {env->lookupName("func"), ctx->fromUTF8String("__code__"), PROTO_NONE}), "__class__"), protoPython::TokenType::Plus /* Unsupported op */, env->lookupName("CodeType"))))) {
#line 298 "source.py"
env->storeName("co_flags", env->getAttr(env->getAttr(env->lookupName("func"), "__code__"), "co_flags"));
#line 307 "source.py"
if (env->isTrue(env->binaryOp(env->lookupName("co_flags"), protoPython::TokenType::BitAnd, ctx->fromInteger(384)))) {
#line 303 "source.py"
throw env->lookupName("func");
;
};
#line 319 "source.py"
if (env->isTrue(env->binaryOp(env->lookupName("co_flags"), protoPython::TokenType::BitAnd, ctx->fromInteger(32)))) {
#line 309 "source.py"
env->storeName("co", env->getAttr(env->lookupName("func"), "__code__"));
#line 311 "source.py"
env->setAttr(env->lookupName("func"), "__code__", env->callObjectEx(env->getAttr(env->lookupName("co"), "replace"), {}, {{"co_flags", env->binaryOp(env->getAttr(env->lookupName("co"), "co_flags"), protoPython::TokenType::BitOr, ctx->fromInteger(256))}}));
#line 312 "source.py"
throw env->lookupName("func");
;
};
;
};
#line 320 "source.py"
{
        const proto::ProtoObject* __mod = env->importModule("functools");
        env->storeName("functools", __mod);
    };
#line 321 "source.py"
{
        const proto::ProtoObject* __mod = env->importModule("_collections_abc");
        env->storeName("_collections_abc", __mod);
    };
#line 322 "source.py"
    const proto::ProtoObject* func_wrapped = ctx->fromMethod(nullptr, py_func_wrapped_31);
    func_wrapped = env->callObject(env->callObject(env->getAttr(env->lookupName("functools"), "wraps"), {env->lookupName("func")}), {func_wrapped});
    env->storeName("wrapped", func_wrapped);
#line 338 "source.py"
throw env->lookupName("wrapped");
    } catch (const proto::ProtoObject* retVal) { return retVal; }
    return PROTO_NONE;
}
extern "C" void* proto_module_init() {
    auto* ctx = protoPython::PythonEnvironment::getCurrentContext();
    auto* env = protoPython::PythonEnvironment::get(ctx);
    if (std::getenv("PROTO_ENV_DIAG")) {
        fprintf(stderr, "[mod] proto_module_init ctx=%p\n", (void*)ctx);
        const proto::ProtoObject* p = env->lookupName("print");
        fprintf(stderr, "[mod] lookupName('print')=%p\n", (void*)p);
        fflush(stderr);
    }

#line 4 "lib/python3.14/types.py"
ctx->fromUTF8String("
Define names for built-in types that aren't directly accessible as a builtin.
");
#line 11 "lib/python3.14/types.py"
{
#line 11 "source.py"
{
        const proto::ProtoObject* __mod = env->importModule("_types", 0, {"*"});
        env->importStar(__mod);
    };
        if (env->hasPendingException()) {
            auto* __exc = env->takePendingException();
            bool __handled = false;
            if (!__handled && env->isException(__exc, env->lookupName("ImportError"))) {
                __handled = true;
#line 14 "source.py"
{
        const proto::ProtoObject* __mod = env->importModule("sys");
        env->storeName("sys", __mod);
    };
#line 15 "source.py"
    const proto::ProtoObject* func__f = ctx->fromMethod(nullptr, py_func__f_1);
    env->storeName("_f", func__f);
#line 16 "source.py"
env->storeName("FunctionType", env->callObject(env->lookupName("type"), {env->lookupName("_f")}));
#line 17 "source.py"
env->storeName("LambdaType", env->callObject(env->lookupName("type"), {ctx->fromMethod(nullptr, [](proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) -> const proto::ProtoObject* {
        auto* env = protoPython::PythonEnvironment::get(ctx);
        // Bind parameters
        unsigned long nPos = args ? args->getSize(ctx) : 0;
        return PROTO_NONE;
    })}));
#line 18 "source.py"
env->storeName("CodeType", env->callObject(env->lookupName("type"), {env->getAttr(env->lookupName("_f"), "__code__")}));
#line 19 "source.py"
env->storeName("MappingProxyType", env->callObject(env->lookupName("type"), {env->getAttr(env->lookupName("type"), "__dict__")}));
#line 20 "source.py"
env->storeName("SimpleNamespace", env->callObject(env->lookupName("type"), {env->getAttr(env->lookupName("sys"), "implementation")}));
#line 22 "source.py"
    const proto::ProtoObject* func__cell_factory = ctx->fromMethod(nullptr, py_func__cell_factory_2);
    env->storeName("_cell_factory", func__cell_factory);
#line 27 "source.py"
env->storeName("CellType", env->callObject(env->lookupName("type"), {env->callObject(env->lookupName("_cell_factory"), {})}));
#line 29 "source.py"
    const proto::ProtoObject* func__g = ctx->fromMethod(nullptr, py_func__g_4);
    env->storeName("_g", func__g);
#line 31 "source.py"
env->storeName("GeneratorType", env->callObject(env->lookupName("type"), {env->callObject(env->lookupName("_g"), {})}));
#line 34 "source.py"
    const proto::ProtoObject* func__c = ctx->fromMethod(nullptr, py_func__c_5);
    env->storeName("_c", func__c);
#line 34 "source.py"
env->storeName("_c", env->callObject(env->lookupName("_c"), {}));
#line 35 "source.py"
env->storeName("CoroutineType", env->callObject(env->lookupName("type"), {env->lookupName("_c")}));
#line 36 "source.py"
env->callObject(env->getAttr(env->lookupName("_c"), "close"), {});
#line 40 "source.py"
    const proto::ProtoObject* func__ag = ctx->fromMethod(nullptr, py_func__ag_6);
    env->storeName("_ag", func__ag);
#line 40 "source.py"
env->storeName("_ag", env->callObject(env->lookupName("_ag"), {}));
#line 41 "source.py"
env->storeName("AsyncGeneratorType", env->callObject(env->lookupName("type"), {env->lookupName("_ag")}));
#line 43 "source.py"

    // Class definition: _C
    const proto::ProtoObject* class_name__C = ctx->fromUTF8String("_C");
    std::vector<const proto::ProtoObject*> bases__C;
    auto* ns__C = const_cast<proto::ProtoObject*>(ctx->newObject(true));
    ns__C->setAttribute(ctx, env->getNameString(), class_name__C);
    {
        auto* oldFrame = protoPython::PythonEnvironment::getCurrentFrame();
        protoPython::PythonEnvironment::setCurrentFrame(ns__C);
#line 44 "source.py"
    const proto::ProtoObject* func__m = ctx->fromMethod(nullptr, py_func__m_7);
    env->storeName("_m", func__m);
        protoPython::PythonEnvironment::setCurrentFrame(oldFrame);
    }
    auto* cls__C = const_cast<proto::ProtoObject*>(ctx->newObject(true));
    if (env->getTypePrototype()) cls__C->setAttribute(ctx, env->getClassString(), env->getTypePrototype());
    for (auto* b : bases__C) cls__C->addParent(ctx, b);
    {
        const proto::ProtoSparseList* keys = ns__C->getAttributes(ctx);
        if (keys) {
            auto it = keys->getIterator(ctx);
            while (it && it->hasNext(ctx)) {
                unsigned long key = it->nextKey(ctx);
                const proto::ProtoObject* keyObj = reinterpret_cast<const proto::ProtoObject*>(key);
                if (keyObj && keyObj->isString(ctx)) {
                    const proto::ProtoString* k = keyObj->asString(ctx);
                    cls__C->setAttribute(ctx, k, ns__C->getAttribute(ctx, k));
                }
                it = const_cast<proto::ProtoSparseListIterator*>(it)->advance(ctx);
            }
        }
    }
    cls__C->setAttribute(ctx, env->getCallString(), ctx->fromMethod(cls__C, [](proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) -> const proto::ProtoObject* {
        auto* env = protoPython::PythonEnvironment::get(ctx);
        auto* obj = const_cast<proto::ProtoObject*>(ctx->newObject(true));
        obj->addParent(ctx, self);
        const proto::ProtoObject* init = env->getAttribute(ctx, obj, env->getInitString());
        if (init && init != PROTO_NONE) {
            std::vector<const proto::ProtoObject*> vargs;
            for (unsigned long i = 0; i < args->getSize(ctx); ++i) vargs.push_back(args->getAt(ctx, i));
            env->callObject(init, vargs);
        }
        return obj;
    }));
    auto var_cls__C = static_cast<const proto::ProtoObject*>(cls__C);
    env->storeName("_C", var_cls__C);
;
#line 45 "source.py"
env->storeName("MethodType", env->callObject(env->lookupName("type"), {env->getAttr(env->callObject(env->lookupName("_C"), {}), "_m")}));
#line 47 "source.py"
env->storeName("BuiltinFunctionType", env->callObject(env->lookupName("type"), {env->lookupName("len")}));
#line 48 "source.py"
env->storeName("BuiltinMethodType", env->callObject(env->lookupName("type"), {env->getAttr(([&]() {
        auto* listObj = static_cast<const proto::ProtoObject*>(ctx->newObject(true));
        auto* lst = ctx->newList();
        listObj->setAttribute(ctx, env->getDataString(), (const proto::ProtoObject*)lst);
        if (env->getListPrototype()) listObj->addParent(ctx, env->getListPrototype());
        return (const proto::ProtoObject*)listObj;
    })(), "append")}));
#line 50 "source.py"
env->storeName("WrapperDescriptorType", env->callObject(env->lookupName("type"), {env->getAttr(env->lookupName("object"), "__init__")}));
#line 51 "source.py"
env->storeName("MethodWrapperType", env->callObject(env->lookupName("type"), {env->getAttr(env->callObject(env->lookupName("object"), {}), "__str__")}));
#line 52 "source.py"
env->storeName("MethodDescriptorType", env->callObject(env->lookupName("type"), {env->getAttr(env->lookupName("str"), "join")}));
#line 53 "source.py"
env->storeName("ClassMethodDescriptorType", env->callObject(env->lookupName("type"), {env->getItem(env->getAttr(env->lookupName("dict"), "__dict__"), ctx->fromUTF8String("fromkeys"))}));
#line 55 "source.py"
env->storeName("ModuleType", env->callObject(env->lookupName("type"), {env->lookupName("sys")}));
#line 58 "source.py"
{
#line 58 "source.py"
env->raiseException(env->lookupName("TypeError"));
        if (env->hasPendingException()) {
            auto* __exc = env->takePendingException();
            bool __handled = false;
            if (!__handled && env->isException(__exc, env->lookupName("TypeError"))) {
                __handled = true;
                env->storeName("exc", __exc);
#line 60 "source.py"
env->storeName("TracebackType", env->callObject(env->lookupName("type"), {env->getAttr(env->lookupName("exc"), "__traceback__")}));
#line 61 "source.py"
env->storeName("FrameType", env->callObject(env->lookupName("type"), {env->getAttr(env->getAttr(env->lookupName("exc"), "__traceback__"), "tb_frame")}));
            }
            if (!__handled) env->raiseException(__exc);
        }
    };
#line 63 "source.py"
env->storeName("GetSetDescriptorType", env->callObject(env->lookupName("type"), {env->getAttr(env->lookupName("FunctionType"), "__code__")}));
#line 64 "source.py"
env->storeName("MemberDescriptorType", env->callObject(env->lookupName("type"), {env->getAttr(env->lookupName("FunctionType"), "__globals__")}));
#line 66 "source.py"
env->storeName("GenericAlias", env->callObject(env->lookupName("type"), {env->getItem(env->lookupName("list"), env->lookupName("int"))}));
#line 67 "source.py"
env->storeName("UnionType", env->callObject(env->lookupName("type"), {env->binaryOp(env->lookupName("int"), protoPython::TokenType::BitOr, env->lookupName("str"))}));
#line 69 "source.py"
env->storeName("EllipsisType", env->callObject(env->lookupName("type"), {env->lookupName("Ellipsis")}));
#line 70 "source.py"
env->storeName("NoneType", env->callObject(env->lookupName("type"), {PROTO_NONE}));
#line 71 "source.py"
env->storeName("NotImplementedType", env->callObject(env->lookupName("type"), {env->lookupName("NotImplemented")}));
#line 76 "source.py"
env->delName("sys");
env->delName("_f");
env->delName("_g");
env->delName("_C");
env->delName("_c");
env->delName("_ag");
env->delName("_cell_factory");
;
            }
            if (!__handled) env->raiseException(__exc);
        }
    };
#line 80 "lib/python3.14/types.py"
    const proto::ProtoObject* func_new_class = ctx->fromMethod(nullptr, py_func_new_class_8);
    env->storeName("new_class", func_new_class);
#line 90 "lib/python3.14/types.py"
    const proto::ProtoObject* func_resolve_bases = ctx->fromMethod(nullptr, py_func_resolve_bases_9);
    env->storeName("resolve_bases", func_resolve_bases);
#line 111 "lib/python3.14/types.py"
    const proto::ProtoObject* func_prepare_class = ctx->fromMethod(nullptr, py_func_prepare_class_10);
    env->storeName("prepare_class", func_prepare_class);
#line 143 "lib/python3.14/types.py"
    const proto::ProtoObject* func__calculate_meta = ctx->fromMethod(nullptr, py_func__calculate_meta_11);
    env->storeName("_calculate_meta", func__calculate_meta);
#line 161 "lib/python3.14/types.py"
    const proto::ProtoObject* func_get_original_bases = ctx->fromMethod(nullptr, py_func_get_original_bases_12);
    env->storeName("get_original_bases", func_get_original_bases);
#line 189 "lib/python3.14/types.py"

    // Class definition: DynamicClassAttribute
    const proto::ProtoObject* class_name_DynamicClassAttribute = ctx->fromUTF8String("DynamicClassAttribute");
    std::vector<const proto::ProtoObject*> bases_DynamicClassAttribute;
    auto* ns_DynamicClassAttribute = const_cast<proto::ProtoObject*>(ctx->newObject(true));
    ns_DynamicClassAttribute->setAttribute(ctx, env->getNameString(), class_name_DynamicClassAttribute);
    {
        auto* oldFrame = protoPython::PythonEnvironment::getCurrentFrame();
        protoPython::PythonEnvironment::setCurrentFrame(ns_DynamicClassAttribute);
#line 206 "source.py"
ctx->fromUTF8String("Route attribute access on a class to __getattr__.

    This is a descriptor, used to define attributes that act differently when
    accessed through an instance and through a class.  Instance access remains
    normal, but access to an attribute through a class will be routed to the
    class's __getattr__ method; this is done by raising AttributeError.

    This allows one to have properties active on an instance, and have virtual
    attributes on the class with the same name.  (Enum used this between Python
    versions 3.4 - 3.9 .)

    Subclass from this to use a different method of accessing virtual attributes
    and still be treated properly by the inspect module. (Enum uses this since
    Python 3.10 .)

    ");
#line 206 "source.py"
    const proto::ProtoObject* func___init__ = ctx->fromMethod(nullptr, py_func___init___13);
    env->storeName("__init__", func___init__);
#line 216 "source.py"
    const proto::ProtoObject* func___get__ = ctx->fromMethod(nullptr, py_func___get___14);
    env->storeName("__get__", func___get__);
#line 225 "source.py"
    const proto::ProtoObject* func___set__ = ctx->fromMethod(nullptr, py_func___set___15);
    env->storeName("__set__", func___set__);
#line 230 "source.py"
    const proto::ProtoObject* func___delete__ = ctx->fromMethod(nullptr, py_func___delete___16);
    env->storeName("__delete__", func___delete__);
#line 235 "source.py"
    const proto::ProtoObject* func_getter = ctx->fromMethod(nullptr, py_func_getter_17);
    env->storeName("getter", func_getter);
#line 241 "source.py"
    const proto::ProtoObject* func_setter = ctx->fromMethod(nullptr, py_func_setter_18);
    env->storeName("setter", func_setter);
#line 246 "source.py"
    const proto::ProtoObject* func_deleter = ctx->fromMethod(nullptr, py_func_deleter_19);
    env->storeName("deleter", func_deleter);
        protoPython::PythonEnvironment::setCurrentFrame(oldFrame);
    }
    auto* cls_DynamicClassAttribute = const_cast<proto::ProtoObject*>(ctx->newObject(true));
    if (env->getTypePrototype()) cls_DynamicClassAttribute->setAttribute(ctx, env->getClassString(), env->getTypePrototype());
    for (auto* b : bases_DynamicClassAttribute) cls_DynamicClassAttribute->addParent(ctx, b);
    {
        const proto::ProtoSparseList* keys = ns_DynamicClassAttribute->getAttributes(ctx);
        if (keys) {
            auto it = keys->getIterator(ctx);
            while (it && it->hasNext(ctx)) {
                unsigned long key = it->nextKey(ctx);
                const proto::ProtoObject* keyObj = reinterpret_cast<const proto::ProtoObject*>(key);
                if (keyObj && keyObj->isString(ctx)) {
                    const proto::ProtoString* k = keyObj->asString(ctx);
                    cls_DynamicClassAttribute->setAttribute(ctx, k, ns_DynamicClassAttribute->getAttribute(ctx, k));
                }
                it = const_cast<proto::ProtoSparseListIterator*>(it)->advance(ctx);
            }
        }
    }
    cls_DynamicClassAttribute->setAttribute(ctx, env->getCallString(), ctx->fromMethod(cls_DynamicClassAttribute, [](proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) -> const proto::ProtoObject* {
        auto* env = protoPython::PythonEnvironment::get(ctx);
        auto* obj = const_cast<proto::ProtoObject*>(ctx->newObject(true));
        obj->addParent(ctx, self);
        const proto::ProtoObject* init = env->getAttribute(ctx, obj, env->getInitString());
        if (init && init != PROTO_NONE) {
            std::vector<const proto::ProtoObject*> vargs;
            for (unsigned long i = 0; i < args->getSize(ctx); ++i) vargs.push_back(args->getAt(ctx, i));
            env->callObject(init, vargs);
        }
        return obj;
    }));
    auto var_cls_DynamicClassAttribute = static_cast<const proto::ProtoObject*>(cls_DynamicClassAttribute);
    env->storeName("DynamicClassAttribute", var_cls_DynamicClassAttribute);
;
#line 252 "lib/python3.14/types.py"

    // Class definition: _GeneratorWrapper
    const proto::ProtoObject* class_name__GeneratorWrapper = ctx->fromUTF8String("_GeneratorWrapper");
    std::vector<const proto::ProtoObject*> bases__GeneratorWrapper;
    auto* ns__GeneratorWrapper = const_cast<proto::ProtoObject*>(ctx->newObject(true));
    ns__GeneratorWrapper->setAttribute(ctx, env->getNameString(), class_name__GeneratorWrapper);
    {
        auto* oldFrame = protoPython::PythonEnvironment::getCurrentFrame();
        protoPython::PythonEnvironment::setCurrentFrame(ns__GeneratorWrapper);
#line 254 "source.py"
    const proto::ProtoObject* func___init__ = ctx->fromMethod(nullptr, py_func___init___20);
    env->storeName("__init__", func___init__);
#line 259 "source.py"
    const proto::ProtoObject* func_send = ctx->fromMethod(nullptr, py_func_send_21);
    env->storeName("send", func_send);
#line 261 "source.py"
    const proto::ProtoObject* func_throw = ctx->fromMethod(nullptr, py_func_throw_22);
    env->storeName("throw", func_throw);
#line 263 "source.py"
    const proto::ProtoObject* func_close = ctx->fromMethod(nullptr, py_func_close_23);
    env->storeName("close", func_close);
#line 266 "source.py"
    const proto::ProtoObject* func_gi_code = ctx->fromMethod(nullptr, py_func_gi_code_24);
    func_gi_code = env->callObject(env->lookupName("property"), {func_gi_code});
    env->storeName("gi_code", func_gi_code);
#line 269 "source.py"
    const proto::ProtoObject* func_gi_frame = ctx->fromMethod(nullptr, py_func_gi_frame_25);
    func_gi_frame = env->callObject(env->lookupName("property"), {func_gi_frame});
    env->storeName("gi_frame", func_gi_frame);
#line 272 "source.py"
    const proto::ProtoObject* func_gi_running = ctx->fromMethod(nullptr, py_func_gi_running_26);
    func_gi_running = env->callObject(env->lookupName("property"), {func_gi_running});
    env->storeName("gi_running", func_gi_running);
#line 275 "source.py"
    const proto::ProtoObject* func_gi_yieldfrom = ctx->fromMethod(nullptr, py_func_gi_yieldfrom_27);
    func_gi_yieldfrom = env->callObject(env->lookupName("property"), {func_gi_yieldfrom});
    env->storeName("gi_yieldfrom", func_gi_yieldfrom);
#line 277 "source.py"
env->storeName("cr_code", env->lookupName("gi_code"));
#line 278 "source.py"
env->storeName("cr_frame", env->lookupName("gi_frame"));
#line 279 "source.py"
env->storeName("cr_running", env->lookupName("gi_running"));
#line 280 "source.py"
env->storeName("cr_await", env->lookupName("gi_yieldfrom"));
#line 281 "source.py"
    const proto::ProtoObject* func___next__ = ctx->fromMethod(nullptr, py_func___next___28);
    env->storeName("__next__", func___next__);
#line 283 "source.py"
    const proto::ProtoObject* func___iter__ = ctx->fromMethod(nullptr, py_func___iter___29);
    env->storeName("__iter__", func___iter__);
#line 287 "source.py"
env->storeName("__await__", env->lookupName("__iter__"));
        protoPython::PythonEnvironment::setCurrentFrame(oldFrame);
    }
    auto* cls__GeneratorWrapper = const_cast<proto::ProtoObject*>(ctx->newObject(true));
    if (env->getTypePrototype()) cls__GeneratorWrapper->setAttribute(ctx, env->getClassString(), env->getTypePrototype());
    for (auto* b : bases__GeneratorWrapper) cls__GeneratorWrapper->addParent(ctx, b);
    {
        const proto::ProtoSparseList* keys = ns__GeneratorWrapper->getAttributes(ctx);
        if (keys) {
            auto it = keys->getIterator(ctx);
            while (it && it->hasNext(ctx)) {
                unsigned long key = it->nextKey(ctx);
                const proto::ProtoObject* keyObj = reinterpret_cast<const proto::ProtoObject*>(key);
                if (keyObj && keyObj->isString(ctx)) {
                    const proto::ProtoString* k = keyObj->asString(ctx);
                    cls__GeneratorWrapper->setAttribute(ctx, k, ns__GeneratorWrapper->getAttribute(ctx, k));
                }
                it = const_cast<proto::ProtoSparseListIterator*>(it)->advance(ctx);
            }
        }
    }
    cls__GeneratorWrapper->setAttribute(ctx, env->getCallString(), ctx->fromMethod(cls__GeneratorWrapper, [](proto::ProtoContext* ctx, const proto::ProtoObject* self, const proto::ParentLink* pl, const proto::ProtoList* args, const proto::ProtoSparseList* kwargs) -> const proto::ProtoObject* {
        auto* env = protoPython::PythonEnvironment::get(ctx);
        auto* obj = const_cast<proto::ProtoObject*>(ctx->newObject(true));
        obj->addParent(ctx, self);
        const proto::ProtoObject* init = env->getAttribute(ctx, obj, env->getInitString());
        if (init && init != PROTO_NONE) {
            std::vector<const proto::ProtoObject*> vargs;
            for (unsigned long i = 0; i < args->getSize(ctx); ++i) vargs.push_back(args->getAt(ctx, i));
            env->callObject(init, vargs);
        }
        return obj;
    }));
    auto var_cls__GeneratorWrapper = static_cast<const proto::ProtoObject*>(cls__GeneratorWrapper);
    env->storeName("_GeneratorWrapper", var_cls__GeneratorWrapper);
;
#line 289 "lib/python3.14/types.py"
    const proto::ProtoObject* func_coroutine = ctx->fromMethod(nullptr, py_func_coroutine_30);
    env->storeName("coroutine", func_coroutine);
#line 340 "lib/python3.14/types.py"
env->storeName("__all__", /* Unsupported node: N11protoPython12ListCompNodeE */);
    return nullptr;
}
