// Generated by protopyc from verify_none.py
#include <protoCore.h>
#include <protoPython/PythonEnvironment.h>
#include <protoPython/Tokenizer.h>
#include <algorithm>

extern "C" void* proto_module_init() {
    auto* ctx = protoPython::PythonEnvironment::getCurrentContext();
    auto* env = protoPython::PythonEnvironment::get(ctx);
    if (std::getenv("PROTO_ENV_DIAG")) {
        fprintf(stderr, "[mod] proto_module_init ctx=%p\n", (void*)ctx);
        const proto::ProtoObject* p = env->lookupName("print");
        fprintf(stderr, "[mod] lookupName('print')=%p\n", (void*)p);
        fflush(stderr);
    }

#line 2 "verify_none.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("bool(None) ="), env->callObject(env->lookupName("bool"), {PROTO_NONE})});
#line 5 "verify_none.py"
if (env->isTrue(PROTO_NONE)) {
#line 4 "source.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("None is truthy! FAIL")});
;
} else {
#line 6 "source.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("None is falsy. SUCCESS")});
;
};
#line 8 "verify_none.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("type(None) ="), env->callObject(env->lookupName("type"), {PROTO_NONE})});
#line 9 "verify_none.py"
env->callObject(env->lookupName("print"), {ctx->fromUTF8String("repr(None) ="), env->callObject(env->lookupName("repr"), {PROTO_NONE})});
    return nullptr;
}
